spring:
  batch:
    jdbc:
      initialize-schema: never
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch2
    username: study
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
      
logging:
  level:
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type.descriptor.sql.BasicBinder]': trace
    '[org.hibernate.type.descriptor.EnumType]': trace